MoneyTransfer/Controllers/TransactionToUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoneyTransfer.Models;

namespace MoneyTransfer.Controllers
{
    public class TransactionToUsersController : Controller
    {

        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public TransactionToUsersController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            IEnumerable<TransactionToUser> transactions = _context.Transactions.Include(t => t.FromAccount).Include(t => t.ToAccount).ToList();

            return View("Index", transactions);
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            User currentUser = await _userManager.FindByEmailAsync(User.Identity.Name);
            ViewBag.PersonalAccount = currentUser.PersonalAccount;
            return View("Create");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransactionToUser transaction)
        {
          
                transaction.DateTime = DateTime.Now;
                _context.Add(transaction);
                User Touser = _context.Users.FirstOrDefault(u => u.PersonalAccount == transaction.ToAccount.PersonalAccount);
                User Fromuser = _context.Users.FirstOrDefault(u => u.PersonalAccount == transaction.FromAccount.PersonalAccount);
                Touser.Balanse += transaction.Sum;
                Fromuser.Balanse -= transaction.Sum;
                await _context.SaveChangesAsync();
            return View("Details",transaction);
        }
    }
}

MoneyTransfer/Views/TransactionToUsers/Create.cshtml
@model MoneyTransfer.Models.TransactionToUser

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Перечислить средства на счёт другого пользователя</h2>

<h4>TransactionToUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ToAccount.PersonalAccount" class="control-label"></label>
                <input asp-for="ToAccount.PersonalAccount" class="form-control" />
                <span asp-validation-for="ToAccount.PersonalAccount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sum" class="control-label"></label>
                <input asp-for="Sum" class="form-control" />
                <span asp-validation-for="Sum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="FromAccount.PersonalAccount" value="@ViewBag.PersonalAccount" />
            </div>
            <div class="form-group">
                <input type="submit" value="Перечислить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

MoneyTransfer/Views/TransactionToUsers/Details.cshtml
@model MoneyTransfer.Models.TransactionToUser
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Details</h2>
<div>
    <h4>TransactionToUser</h4>
    <hr />
    <dl
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sum)
        </dd>
        <dt>
               Счет отправителя
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ToAccount.PersonalAccount)
        </dd>
        <dt>
            Счет получателя
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FromAccount.PersonalAccount)
        </dd>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <div>
         <a asp-action="Index">Список транзакций</a>
    </div>
</div>

MoneyTransfer/Views/TransactionToUsers/Index.cshtml
@model IEnumerable<MoneyTransfer.Models.TransactionToUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Список транзакций</h2>

<p>
    <a asp-controller="TransactionToUsers" asp-action="Create">Перечислить средства на другой счет</a>

</p>
<table class="table">
    <thead>
        <tr>
                <th>
                   Отправитель
                </th>
                <th>
                    Получатель
                </th>
                <th>
                    Дата
                </th>
                <th>
                   Сумма
                </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ToAccount.PersonalAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FromAccount.PersonalAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sum)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>